//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAccaunting.model
{
    using System;
    using System.Collections.Generic;

    public partial class sklads 
    {

        public int Id { get; set; }
        public string Postavshik { get; set; }
        public string Tovar { get; set; }
        public decimal stoimost { get; set; }
        public System.DateTime datapostuplen { get; set; }
       

    }
}
