//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppAccaunting.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakazies
    {
        public int Id { get; set; }
        public string Zakazchik { get; set; }
        public string TovarZ { get; set; }
        public System.DateTime Datazakaza { get; set; }
        public int CountZ { get; set; }
        public decimal Stoimost { get; set; }
    }
}
